$(function(){var a=$(".col-md-2 .sidebar");320>=window.innerWidth&&($("body").css("fontSize","95%"),$("button").css("fontSize","85%"));/iPhone|iPod|iPad/i.test(navigator.userAgent)&&$(".btn-quick-guide").css("display","none");$("#pull").unbind("click").on("click",function(c){c.preventDefault();c.stopPropagation();window.scrollTo(0,0);a.toggle("slide")})});
(function(a){a.extend({scrollToTop:function(){var c=!1;a("body").append(a("<a />").addClass("scroll-to-top").attr({href:"#",id:"scrollToTop"}).append(a("<i />").addClass("icon icon-chevron-up icon-white")));a("#scrollToTop").click(function(c){c.preventDefault();a("body, html").animate({scrollTop:0},500);return!1});a(window).scroll(function(){var b=a(window).scrollTop();35>b?a("#pull").attr("style","top: 24px!important"):35<b&&(b-=10,a("#pull").attr("style","top: "+b+"px!important"));c||(c=!0,150<
a(window).scrollTop()?a("#scrollToTop").stop(!0,!0).addClass("visible"):a("#scrollToTop").stop(!0,!0).removeClass("visible"),c=!1)})}})})(jQuery);
(function(a){var c={action:function(){},runOnLoad:!1,duration:500},b=!1,e,d={init:function(){for(var b=0;b<=arguments.length;b++){var e=arguments[b];switch(typeof e){case "function":c.action=e;break;case "boolean":c.runOnLoad=e;break;case "number":c.duration=e}}return this.each(function(){c.runOnLoad&&c.action();a(this).resize(function(){d.timedAction.call(this)})})},timedAction:function(a,d){var k=function(){var a=c.duration;if(b&&(a=c.duration-(new Date-e),0>=a)){clearTimeout(b);b=!1;c.action();
return}b=setTimeout(k,a)};e=new Date;"number"===typeof d&&(c.duration=d);"function"===typeof a&&(c.action=a);b||k()}};a.fn.afterResize=function(a){return d[a]?d[a].apply(this,Array.prototype.slice.call(arguments,1)):d.init.apply(this,arguments)}})(jQuery);
(function(){var a={initialized:!1,initialize:function(){this.initialized||(this.initialized=!0,this.build(),this.events())},build:function(){$.scrollToTop();this.featuredBoxes();this.toggle()},events:function(){$(window).afterResize(function(){a.featuredBoxes();a.checkStickyMenu()})},stickyMenu:function(){if($("body").hasClass("boxed"))return!1;var a=$("body header:first"),b=a.height(),e=a.find(".logo"),d=a.find(".logo img"),h=d.width(),n=d.height(),k=this;d.css("height",40);var p=d.width();d.css("height",
"auto").css("width","auto");var f=$("header.flat-menu ul.nav-main > li > a");k.checkStickyMenu=function(){if($("body").hasClass("boxed"))return!1;if($(window).scrollTop()>b-15-40&&991<$(window).width()){if($("body").hasClass("sticky-menu-active"))return!1;d.stop(!0,!0);$("body").addClass("sticky-menu-active").css("padding-top",b);f.addClass("sticky-menu-active");e.addClass("logo-sticky-active");d.animate({width:p,height:40,top:"28px"},200,function(){})}else $("body").hasClass("sticky-menu-active")&&
($("body").removeClass("sticky-menu-active").css("padding-top",0),f.removeClass("sticky-menu-active"),e.removeClass("logo-sticky-active"),d.animate({width:h,height:n,top:"0px"},200,function(){d.css({width:"auto",height:"auto"})}))};$(window).on("scroll",function(){k.checkStickyMenu()});k.checkStickyMenu()},featuredBoxes:function(){$("div.featured-box").css("height","auto");$("div.featured-boxes").each(function(){var a=$(this),b=0;$("div.featured-box",a).each(function(){$(this).height()>b&&(b=$(this).height())});
$("div.featured-box",a).height(b)})},toggle:function(){$("section.toggle > label").prepend($("<i />").addClass("icon icon-plus"));$("section.toggle > label").prepend($("<i />").addClass("icon icon-minus"));$("section.toggle.active > p").addClass("preview-active");$("section.toggle.active > div.toggle-content").slideDown(350,function(){});$("section.toggle > label").click(function(a){var b=$(this).parent(),e=$(this).parents("div.toogle"),d=!1;e.hasClass("toogle-accordion")&&"undefined"!=typeof a.originalEvent&&
e.find("section.toggle.active > label").trigger("click");b.toggleClass("active");if(b.find("> p").get(0)){d=b.find("> p");a=d.css("height");d.css("height","auto");var h=d.css("height");d.css("height",a)}a=b.find("> div.toggle-content");b.hasClass("active")?($(d).animate({height:h},350,function(){$(this).addClass("preview-active")}),a.slideDown(350,function(){})):($(d).animate({height:25},350,function(){$(this).removeClass("preview-active")}),a.slideUp(350,function(){}))})}};a.initialize();$(window).load(function(){a.stickyMenu()})})();
(function(a){a.TryIt=function(c,b){var e={url:c},d=this;d.settings={};d.compile=function(){a(".prettyprint.tryit").click(function(b){var e=a(this).text(),c="",f="",h="",m="",l="";if(a(this).attr("title")){var g=a(this).attr("title").split(",");g[0]&&(c=a("#"+g[0].trim()+"").text());g[1]&&(f=a("#"+g[1].trim()+"").text());g[2]&&(l=g[2],h=a("#"+g[2].trim()+"").text());g[3]&&(l=g[3],m=a("#"+g[3].trim()+"").text())}a("#source").text(e);a("#supportsource").text(c);a("#utilsource").text(f);a("#extrasource").text(h);
a("#inputs").text(m);a("#filename").text(l);e=a(this).width()+12;a(this).height();c=a(this).offset().left;f=a(this).offset().top;c=Math.round(c);c=b.pageX-c;X=e-c;f=Math.round(f);f=b.pageY-f;36>=X&&36>=f&&(b.preventDefault(),768>=window.innerWidth?(b=window.innerHeight,a.colorbox({iframe:!0,reposition:!0,opacity:.35,href:d.settings.url,width:window.innerWidth,height:b})):(a(window).height(),a.colorbox({iframe:!0,reposition:!0,opacity:.35,href:d.settings.url,width:960,height:650})))})};var h=a(window).innerWidth()/
2-320;a(".inline").colorbox({inline:!0,left:h,width:"615px",opacity:.5});(function(){d.settings=a.extend({},e,b);a("body").append('<div id="source" style="display:none;"></div>');a("body").append('<div id="supportsource" style="display:none;"></div>');a("body").append('<div id="utilsource" style="display:none;"></div>');a("body").append('<div id="extrasource" style="display:none;"></div>');a("body").append('<div id="inputs" style="display:none;"></div>');a("body").append('<div id="filename" style="display:none;"></div>');
a(".prettyprint.tryit").mousemove(function(b){var c=a(this).width()+12;a(this).height();var d=a(this).offset().left,e=a(this).offset().top,d=Math.round(d),d=b.pageX-d;X=c-d;e=Math.round(e);e=b.pageY-e;36>=X&&36>=e?a(this).css("cursor","pointer"):a(this).css("cursor","default")})})()}})(jQuery);
$(document).ready(function(){var a=location.href;filename=a.substring(a.lastIndexOf(".com")+5);-1==filename.lastIndexOf(".htm")&&(filename+="index.htm");0==$('.sidebar li a[href*= "'+filename+'"]').text().length&&(filename=$(".parent-file").text());if(-1==filename.lastIndexOf("whoiswho")){$('.sidebar li a[href*= "'+filename+'"]').css("color","");$('.sidebar li a[href*= "'+filename+'"]').css("background-color","#d6d6d6");var c=!1,b=!1;$(document).on("click",".cclose",function(a){$(".submenu-item").hide()});
$("#liTL").click(function(a){a.stopPropagation();$.ajax({url:"tutorials-submenu.htm"}).done(function(a){$("#top-sub-menu").html(a);c?($(".submenu-item").hide(),c=!1):($(".submenu-item").show(),c=!0,b=!1)})});$("#liCG").click(function(a){a.stopPropagation();$.ajax({url:"codingground-submenu.htm"}).done(function(a){$("#top-sub-menu").html(a);b?($(".submenu-item").hide(),b=!1):($(".submenu-item").show(),b=!0,c=!1)})});$(document).on("click",function(a){a=$(".submenu-item");a.is(":visible")&&a.hide()});
$(".no-sub-menu").on("click",function(a){a=$(".submenu-item");a.is(":visible")&&a.hide()})}});$(window).load(function(){$(".middle-col").height()<$(".sidebar").height()&&991<window.innerWidth&&$(".middle-col").css("height",$(".sidebar").height()+50);$(".middle-col").height()<$("#rightbar").height()&&991<window.innerWidth&&$(".middle-col").css("height","1171");/iPhone|iPad|iPod/i.test(navigator.userAgent)&&($(".android").hide(),$(".microsoft").hide(),$(".hide-me").hide())});
function resizeFrame(a){a.height="0px";a.height=a.contentWindow.document.body.scrollHeight+5+"px"}468>window.innerWidth&&($(".topgooglead").html(""),$(".topgooglead").html('<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js">\x3c/script><ins class="adsbygoogle"     style="display:inline-block;width:300px;height:250px"     data-ad-client="ca-pub-7133395778201029"    data-ad-slot="8354544120"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});\x3c/script>'));